import type { SecurityScenario, ScenarioCompany, ScenarioLossProfile } from "./schema";

const DEFAULT_COMPANY: ScenarioCompany = {
  name: "Fictional Global Enterprises",
  sector: "Diversified manufacturing & services",
  description:
    "A diversified mid‑cap enterprise with a mix of legacy platforms and modern SaaS, operating across North America and Europe.",
  annualRevenueMillions: 2500,
  ebitdaMarginPercent: 18,
  region: "Global",
  headquarters: "Various",
  employeeCount: 5000,
  foundedYear: 1985,
  infrastructure: "Mixed legacy and cloud infrastructure",
  history: "Established through multiple acquisitions and organic growth",
};

const DEFAULT_LOSS: ScenarioLossProfile = {
  grossP90Millions: 140,
  netP90Millions: 45,
  meanLossMillions: 28,
  frequencyPerYear: 0.6,
  topDriver: "Privilege misuse into legacy core systems",
};

export const SECURITY_SCENARIOS: SecurityScenario[] = [
  {
    id: "na-ransomware-ibmi",
    index: 1,
    title: "Ransomware on legacy IBM i core",
    shortTitle: "Legacy core ransomware",
    category: "Ransomware · Legacy platform",
    severity: "high",
    countryCode: "US",
    countryName: "United States",
    latitude: 42.33,
    longitude: -83.05,
    company: {
      ...DEFAULT_COMPANY,
      name: "Heritage Manufacturing Group",
      sector: "Industrial manufacturing",
      description:
        "A heritage manufacturer running its settlement and inventory on IBM i, with decades of technical debt around file shares and domain trusts. The company operates 12 manufacturing facilities across North America, with centralized ERP and inventory management on IBM i Power9 systems. Revenue is concentrated in automotive parts and industrial equipment, with significant exposure to supply chain disruptions. The IBM i environment hosts critical applications including order-to-cash, inventory management, and financial reporting. Legacy Windows file shares provide integration points for plant-floor systems and external partners, creating a complex trust boundary that has evolved organically over 20+ years.",
      annualRevenueMillions: 3200,
      ebitdaMarginPercent: 14,
      region: "North America",
      headquarters: "Detroit, Michigan, USA",
      employeeCount: 8400,
      foundedYear: 1972,
      infrastructure:
        "IBM i Power9 core systems (12 partitions), Windows Server domain (200+ servers), plant-floor SCADA networks, hybrid cloud SaaS integrations",
      history:
        "Founded in 1972 as a regional automotive parts supplier. Expanded through acquisitions in the 1990s-2000s, integrating multiple ERP systems onto a single IBM i platform. Current infrastructure reflects 50+ years of organic growth and M&A activity.",
    },
    lossProfile: {
      ...DEFAULT_LOSS,
      grossP90Millions: 180,
      netP90Millions: 60,
      meanLossMillions: 35,
      frequencyPerYear: 0.8,
      topDriver: "Ransomware propagation via legacy Windows‑to‑IBM i file shares",
    },
    metrics: {
      controlAdoption: 72,
      incidentRate: 18,
      successIndex: 52,
      welfareDebt: 80,
      systemReversibility: 20,
      debtIndex: 13,
    },
    fairFocus: "Loss magnitude (P90) and control impact on LEF.",
    steps: [
      {
        id: "intro",
        title: "Shadow file shares into the core",
        messages: [
          "You're running IBM i 7.4, and you have several Windows shares mapped directly to the root of the Integrated File System (IFS).",
          "As BreachGuard LLM, I need to highlight a critical inheritance problem here: these mappings bypass IBM i object-level security.",
          "When Windows users access \\\\ibmi-server\\ifs-root, they're hitting the IFS with the authority of the QSYS user profile that owns the SMB service—often QSYS or a service account with *ALLOBJ special authority.",
          "A ransomware crew has already landed in your Windows domain and is probing these mapped drives. They're looking for writable directories in the IFS that could let them drop encryption payloads or pivot into QSYS libraries.",
          "The IFS root mapping means they don't need to understand IBM i object authority—they just need write access to any folder in that share.",
          "Once they encrypt files in the IFS, your IBM i applications that depend on those files will fail. Recovery requires restoring from backups, but if your backup strategy assumes 'IBM i is secure by default,' you may not have tested full IFS recovery scenarios.",
          "This is a classic inheritance problem: the file share pattern was set up decades ago when the threat model was different, and now it's exposing your core business logic to Windows-borne threats.",
        ],
        prompt: "How do you want to frame this scenario?",
        choices: [
          {
            id: "loss-driven",
            label: "Start with potential loss exposure",
            summary: "Quantify plausible direct and indirect loss (FAIR P90, revenue at risk) before debating controls. Helps the board see financial impact.",
            metricDeltas: { successIndex: 5, welfareDebt: -2 },
          },
          {
            id: "control-driven",
            label: "Start with missing controls",
            summary: "Jump straight into encryption, segmentation, and logging gaps. Raises control adoption and reduces governance debt.",
            metricDeltas: { controlAdoption: 4, welfareDebt: -3, debtIndex: -2 },
          },
          {
            id: "recovery-first",
            label: "Prioritize recovery and backup validation",
            summary: "Focus on IFS recovery testing and RTO validation. Reduces incident impact and improves reversibility.",
            metricDeltas: { systemReversibility: 6, successIndex: 3, incidentRate: -2 },
          },
        ],
      },
      {
        id: "round-1",
        title: "First containment decision",
        messages: [
          "Initial detections show encryption activity in a legacy file share mapped to /ifs-root/inventory.",
          "The security audit journal (QAUDJRN) shows file opens and writes from the SMB service account, but you don't have real-time alerting on IFS changes.",
          "You can either freeze SMB access to the IFS immediately (which will break Windows users' access to shared reports and data exports) or wait for more telemetry to confirm this isn't a false positive.",
          "However, waiting risks the ransomware spreading to other IFS directories, potentially including QSYS libraries if the service account has broader authority than expected.",
        ],
        prompt: "What do you propose?",
        choices: [
          {
            id: "aggressive-contain",
            label: "Aggressive containment: cut SMB access to IFS now",
            summary: "Immediately disconnect Windows–IFS mappings. Reduces incident spread and governance debt; may cause operational disruption.",
            metricDeltas: { incidentRate: -5, welfareDebt: -4, successIndex: 6, controlAdoption: 2 },
          },
          {
            id: "observe-longer",
            label: "Observe longer to reduce false positives",
            summary: "Gather more telemetry before acting. Risks spread; increases incident rate and debt.",
            metricDeltas: { incidentRate: 4, welfareDebt: 5, successIndex: -6, debtIndex: 3 },
          },
          {
            id: "isolate-inventory",
            label: "Isolate only the affected inventory share and add alerting",
            summary: "Narrow containment plus real-time IFS monitoring. Balanced impact on risk and operations.",
            metricDeltas: { incidentRate: -2, welfareDebt: -2, successIndex: 4, controlAdoption: 5, systemReversibility: 2 },
          },
        ],
      },
      {
        id: "round-2",
        title: "Post-incident posture",
        messages: [
          "Containment is in place. Leadership wants a clear plan to prevent recurrence and to align IFS security with FAIR-style loss exposure.",
          "Options include: full IFS access review and least-privilege redesign, mandatory recovery drills, or accepting residual risk with enhanced monitoring.",
        ],
        prompt: "How do you strengthen posture going forward?",
        choices: [
          {
            id: "least-privilege-ifs",
            label: "Redesign IFS access with least privilege and remove root mapping",
            summary: "Eliminate broad SMB-to-IFS mapping; use dedicated shares per application. Strong improvement in control adoption and reversibility.",
            metricDeltas: { controlAdoption: 8, welfareDebt: -6, systemReversibility: 5, successIndex: 6 },
          },
          {
            id: "recovery-drills",
            label: "Mandate quarterly IFS recovery drills and update RTOs",
            summary: "Validate backup and restore; document RTO. Improves reversibility and success index.",
            metricDeltas: { systemReversibility: 7, successIndex: 5, incidentRate: -2 },
          },
          {
            id: "monitor-only",
            label: "Enhance monitoring and accept residual risk for now",
            summary: "Add alerting and defer structural change. Small control gain; debt and incident rate stay elevated.",
            metricDeltas: { controlAdoption: 3, welfareDebt: 2, debtIndex: 2 },
          },
        ],
      },
    ],
    resources: [
      {
        id: "ibmi-redbook-security",
        label: "IBM i Security Reference (IBM Redbooks)",
        url: "https://www.redbooks.ibm.com/abstracts/sg247497.html",
      },
      {
        id: "ibmi-ifs-overview",
        label: "Integrated File System (IFS) concepts on IBM i",
        url: "https://www.ibm.com/docs/en/i/7.5?topic=programming-integrated-file-system",
      },
      {
        id: "ransomware-ibmi-article",
        label: "Ransomware risks to IBM i environments (article)",
        url: "https://www.ibm.com/blog/ransomware-and-ibm-i-security/",
      },
    ],
  },
  {
    id: "uk-saas-vendor-breach",
    index: 2,
    title: "SaaS vendor breach leaking privileged credentials",
    shortTitle: "Vendor credential spill",
    category: "Third‑party · SaaS",
    severity: "high",
    countryCode: "GB",
    countryName: "United Kingdom",
    latitude: 51.5074,
    longitude: -0.1278,
    company: {
      ...DEFAULT_COMPANY,
      name: "Regency Financial Services",
      sector: "Regional financial services",
      description:
        "A regional financial services firm with heavy reliance on SaaS integrations into core finance and risk systems. The company operates across the UK and EU, serving mid-market commercial clients with lending, treasury, and trade finance products. Annual revenue of £850M with an EBITDA margin around 22%. Core systems include a legacy core banking platform augmented by modern SaaS tools for CRM, risk analytics, and regulatory reporting. The finance integration vendor provides real-time GL posting and multi-entity consolidation, making it a critical dependency. The firm has grown through acquisition, leading to a complex integration landscape where vendor APIs bridge legacy and cloud systems.",
      annualRevenueMillions: 1100,
      ebitdaMarginPercent: 22,
      region: "UK & EU",
      headquarters: "London, United Kingdom",
      employeeCount: 3200,
      foundedYear: 1988,
      infrastructure:
        "Legacy core banking platform (mainframe), modern SaaS stack (Salesforce, Workday, vendor finance APIs), hybrid cloud architecture",
      history:
        "Established in 1988 as a regional building society. Converted to a commercial bank in 2005. Expanded across EU through acquisitions (2010-2018), integrating multiple core systems onto a unified platform.",
    },
    lossProfile: {
      ...DEFAULT_LOSS,
      grossP90Millions: 120,
      netP90Millions: 38,
      meanLossMillions: 24,
      frequencyPerYear: 0.7,
      topDriver: "Third‑party privileged access into core finance platform",
    },
    metrics: {
      controlAdoption: 65,
      incidentRate: 22,
      successIndex: 48,
      welfareDebt: 76,
      systemReversibility: 28,
      debtIndex: 18,
    },
    fairFocus: "Third-party risk and loss exposure (blast radius).",
    steps: [
      {
        id: "intro",
        title: "Privileged integration gone sideways",
        messages: [
          "Your finance integration relies on a SaaS vendor's API that has write access to your core general ledger and accounts payable systems.",
          "The vendor has disclosed a breach where API credentials were exfiltrated. These credentials use OAuth 2.0 client credentials flow with a scope that grants 'finance:write'—meaning an attacker could potentially create fraudulent journal entries, modify payment instructions, or alter vendor master data.",
          "The integration runs on a scheduled batch job that syncs transactions every hour, but the API credentials also support ad-hoc queries and writes.",
          "Your security team has never fully mapped which systems downstream depend on this vendor's data, and the vendor's incident response timeline suggests the credentials may have been exposed for weeks before detection.",
          "This is a third-party risk inheritance problem: you outsourced a critical integration without maintaining visibility into the blast radius if that vendor's security posture degrades.",
        ],
        prompt: "Where do you want to focus first?",
        choices: [
          {
            id: "surface-blast-radius",
            label: "Map blast radius and dependent systems",
            summary: "Identify all systems that depend on the compromised credentials. Reduces governance debt and improves success index.",
            metricDeltas: { successIndex: 6, welfareDebt: -4, debtIndex: -2 },
          },
          {
            id: "public-messaging",
            label: "Draft external comms and disclosures",
            summary: "Prepare regulatory and customer communications. Helps contain reputational impact and incident rate.",
            metricDeltas: { incidentRate: -3, successIndex: 3 },
          },
          {
            id: "rotate-and-restrict",
            label: "Rotate credentials and restrict API scope immediately",
            summary: "Revoke exposed credentials and narrow scope to minimum required. Strong control adoption and debt reduction.",
            metricDeltas: { controlAdoption: 6, welfareDebt: -5, incidentRate: -2, successIndex: 4 },
          },
        ],
      },
      {
        id: "round-1",
        title: "Vendor and internal coordination",
        messages: [
          "Blast radius mapping shows the finance integration touches GL, AP, and three downstream reporting systems. The vendor has issued new credentials but has not yet implemented scope reduction.",
          "You need to decide how to coordinate with the vendor and what to require before re-enabling the integration.",
        ],
        prompt: "How do you coordinate and what do you require?",
        choices: [
          {
            id: "require-scope-reduction",
            label: "Require vendor to implement least-privilege API scope before re-enabling",
            summary: "No integration until scope is reduced. Improves control adoption and long-term reversibility.",
            metricDeltas: { controlAdoption: 7, systemReversibility: 4, welfareDebt: -4, successIndex: 5 },
          },
          {
            id: "re-enable-with-monitoring",
            label: "Re-enable with enhanced monitoring and quarterly access reviews",
            summary: "Resume integration with new creds and add monitoring. Moderate improvement; some debt remains.",
            metricDeltas: { controlAdoption: 4, incidentRate: -2, welfareDebt: -2 },
          },
          {
            id: "accept-residual",
            label: "Accept residual risk and document for insurance and audit",
            summary: "Document decision and residual risk. Small control gain; debt and incident rate stay higher.",
            metricDeltas: { successIndex: 2, welfareDebt: 2, debtIndex: 2 },
          },
        ],
      },
      {
        id: "round-2",
        title: "Long-term third-party risk posture",
        messages: [
          "The immediate incident is contained. Leadership wants to know how third-party and vendor risk will be managed so that FAIR loss exposure stays within appetite.",
        ],
        prompt: "How do you strengthen third-party risk management?",
        choices: [
          {
            id: "vendor-risk-program",
            label: "Stand up a formal vendor risk program with FAIR-style loss exposure",
            summary: "Define vendor tiers, required controls, and loss exposure by vendor. Strong governance and success index.",
            metricDeltas: { controlAdoption: 6, welfareDebt: -6, successIndex: 6, debtIndex: -3 },
          },
          {
            id: "critical-only",
            label: "Focus on critical vendors only and annual reviews",
            summary: "Formalize only for critical integrations. Moderate improvement in control and debt.",
            metricDeltas: { controlAdoption: 4, welfareDebt: -3, successIndex: 3 },
          },
          {
            id: "defer-program",
            label: "Defer program and rely on contract and insurance",
            summary: "No formal program yet; rely on contracts and cyber insurance. Debt and incident rate remain elevated.",
            metricDeltas: { welfareDebt: 3, debtIndex: 3, successIndex: -2 },
          },
        ],
      },
    ],
    resources: [
      {
        id: "shared-responsibility-saas",
        label: "Shared responsibility in SaaS security (NCSC guidance)",
        url: "https://www.ncsc.gov.uk/collection/cloud-security",
      },
      {
        id: "vendor-risk-program",
        label: "Vendor and third‑party risk management practices",
        url: "https://www.ffiec.gov/press/pr031015.htm",
      },
    ],
  },
  {
    id: "de-industrial-control",
    index: 3,
    title: "Legacy industrial control network bridging into IT",
    shortTitle: "OT / IT bridge",
    category: "Operational technology",
    severity: "medium",
    countryCode: "DE",
    countryName: "Germany",
    latitude: 52.3759,
    longitude: 9.732,
    company: {
      ...DEFAULT_COMPANY,
      name: "Continental Automotive Systems",
      sector: "Automotive manufacturing",
      description:
        "A major automotive supplier operating manufacturing plants across Germany and Eastern Europe. Revenue of €4.2B with 16% EBITDA margin. Production systems rely on Programmable Logic Controllers (PLCs) and SCADA systems that historically bridged directly into the corporate IT network for production reporting and maintenance access. The OT environment includes legacy controllers running proprietary protocols, with some newer systems using Ethernet/IP. The flat network architecture was designed for operational simplicity but creates a direct path from plant-floor systems to corporate ERP and email systems.",
      annualRevenueMillions: 4600,
      ebitdaMarginPercent: 16,
      region: "EU",
      headquarters: "Hanover, Germany",
      employeeCount: 18500,
      foundedYear: 1871,
      infrastructure:
        "OT networks (PLCs, SCADA), corporate IT network, ERP systems (SAP), plant-floor integration systems, hybrid cloud infrastructure",
      history:
        "Founded in 1871 as a rubber manufacturer. Evolved into automotive supplier through acquisitions and organic growth. Current infrastructure reflects decades of industrial automation evolution.",
    },
    lossProfile: {
      ...DEFAULT_LOSS,
      grossP90Millions: 95,
      netP90Millions: 32,
      meanLossMillions: 18,
      frequencyPerYear: 0.5,
      topDriver: "OT-to-IT bridge enabling ransomware propagation into production systems",
    },
    metrics: {
      controlAdoption: 58,
      incidentRate: 16,
      successIndex: 46,
      welfareDebt: 72,
      systemReversibility: 24,
      debtIndex: 21,
    },
    fairFocus: "OT/IT boundary and threat event frequency (TEF).",
    steps: [
      {
        id: "intro",
        title: "Flat network between plant and core",
        messages: [
          "Your manufacturing plant uses a flat network architecture where Operational Technology (OT) controllers and SCADA systems share the same Layer 2 domain as corporate IT.",
          "A wormable exploit targeting industrial control systems is circulating in similar automotive manufacturing environments. The exploit propagates via SMB and can compromise PLCs and HMIs, then pivot into the corporate domain through the shared network.",
          "Your production systems depend on real-time data from the corporate ERP for material planning and quality tracking, so network segmentation would require redesigning these integrations.",
          "However, the flat network means a single compromised device in the plant could potentially reach your core business systems.",
          "This is an OT/IT convergence inheritance problem: the network was designed when OT and IT were separate kingdoms, and now they're tightly coupled without proper security boundaries.",
        ],
        prompt: "How do you respond to the OT/IT bridge risk?",
        choices: [
          {
            id: "segment-now",
            label: "Segment aggressively and accept downtime risk",
            summary: "Implement network segmentation between OT and IT immediately. Reduces incident rate and governance debt; may cause production disruption.",
            metricDeltas: { incidentRate: -5, welfareDebt: -5, successIndex: 5, controlAdoption: 4 },
          },
          {
            id: "phased-segment",
            label: "Phased segmentation with temporary compensating controls",
            summary: "Plan segmentation in phases; add monitoring and egress filtering in the meantime. Balanced impact.",
            metricDeltas: { incidentRate: -2, welfareDebt: -3, successIndex: 4, systemReversibility: 3 },
          },
          {
            id: "accept-and-document",
            label: "Accept risk and document for insurance; defer segmentation",
            summary: "Document residual risk and defer structural change. Incident rate and debt stay high.",
            metricDeltas: { welfareDebt: 4, debtIndex: 4, successIndex: -3 },
          },
        ],
      },
      {
        id: "round-1",
        title: "Containment and production impact",
        messages: [
          "An exploit has been detected in one plant. You can isolate the affected plant, isolate only the compromised segment, or allow operations to continue with enhanced monitoring.",
        ],
        prompt: "How do you contain the incident?",
        choices: [
          {
            id: "isolate-plant",
            label: "Isolate the affected plant from corporate IT immediately",
            summary: "Full isolation to prevent spread. Strong reduction in incident rate and debt; production impact.",
            metricDeltas: { incidentRate: -6, welfareDebt: -4, successIndex: 6, controlAdoption: 2 },
          },
          {
            id: "isolate-segment",
            label: "Isolate only the compromised OT segment and increase monitoring",
            summary: "Targeted containment. Good balance of risk reduction and operations.",
            metricDeltas: { incidentRate: -3, welfareDebt: -2, successIndex: 4, systemReversibility: 2 },
          },
          {
            id: "monitor-only",
            label: "Enhanced monitoring only; keep production running",
            summary: "Minimize disruption; risk of spread remains. Incident rate and debt increase.",
            metricDeltas: { incidentRate: 3, welfareDebt: 3, successIndex: -4 },
          },
        ],
      },
      {
        id: "round-2",
        title: "Long-term OT/IT security posture",
        messages: [
          "Leadership wants a sustainable OT/IT security model that keeps loss exposure (FAIR P90) within appetite while allowing production to run.",
        ],
        prompt: "How do you strengthen OT/IT posture long term?",
        choices: [
          {
            id: "full-dmz",
            label: "Implement OT/IT DMZ and asset inventory",
            summary: "Full DMZ, asset inventory, and patch cadence. Strong control adoption and reversibility.",
            metricDeltas: { controlAdoption: 8, systemReversibility: 6, welfareDebt: -6, successIndex: 6 },
          },
          {
            id: "critical-paths-only",
            label: "Harden critical paths only; document residual risk",
            summary: "Secure only the most critical integration paths. Moderate improvement.",
            metricDeltas: { controlAdoption: 4, welfareDebt: -3, successIndex: 3 },
          },
          {
            id: "outsource-assessment",
            label: "Commission external assessment and defer major change",
            summary: "Get an external view; defer structural change. Small gains; debt remains.",
            metricDeltas: { successIndex: 2, welfareDebt: 1, debtIndex: 2 },
          },
        ],
      },
    ],
    resources: [
      {
        id: "ot-it-segmentation",
        label: "NIST Guide to Operational Technology Security",
        url: "https://www.nist.gov/publications/guide-operational-technology-security",
      },
      {
        id: "isa-iec62443",
        label: "ISA/IEC 62443 Industrial Automation and Control Systems Security",
        url: "https://www.isa.org/standards-and-publications/isa-standards/isa-iec-62443-series-of-standards",
      },
    ],
  },
  {
    id: "in-outsourced-helpdesk",
    index: 4,
    title: "Outsourced helpdesk with privileged reset paths",
    shortTitle: "Helpdesk inheritance",
    category: "Identity & access",
    severity: "medium",
    countryCode: "IN",
    countryName: "India",
    latitude: 12.9716,
    longitude: 77.5946,
    company: {
      ...DEFAULT_COMPANY,
      name: "GlobalTech Services India",
      sector: "IT services & outsourcing",
      description:
        "A large IT services provider based in India, serving global clients with helpdesk, application support, and infrastructure management. Revenue of $1.8B with 28% EBITDA margin. The company operates multiple service centers across India, providing 24/7 support to clients in North America, Europe, and APAC. Helpdesk operations use a mix of modern ticketing systems and legacy scripts for password resets and account provisioning. The privileged reset functionality was built years ago to handle high-volume password reset requests efficiently, but it bypasses modern identity governance controls and relies on service accounts with broad authority.",
      annualRevenueMillions: 1800,
      ebitdaMarginPercent: 28,
      region: "Global (India-based)",
      headquarters: "Bangalore, India",
      employeeCount: 12500,
      foundedYear: 1995,
      infrastructure:
        "Multi-tenant service delivery platform, helpdesk ticketing systems, identity management systems, client VPN infrastructure, cloud-based collaboration tools",
      history:
        "Founded in 1995 as a regional IT support provider. Expanded globally through organic growth and strategic acquisitions. Current operations span multiple service centers across India.",
    },
    lossProfile: {
      ...DEFAULT_LOSS,
      grossP90Millions: 65,
      netP90Millions: 22,
      meanLossMillions: 12,
      frequencyPerYear: 0.4,
      topDriver: "Insider threat via outsourced helpdesk with privileged reset capabilities",
    },
    metrics: {
      controlAdoption: 61,
      incidentRate: 20,
      successIndex: 50,
      welfareDebt: 70,
      systemReversibility: 30,
      debtIndex: 17,
    },
    fairFocus: "Insider and third-party privilege driving LEF and LM.",
    steps: [
      {
        id: "intro",
        title: "Password reset scripts as an attack surface",
        messages: [
          "Your outsourced helpdesk uses legacy PowerShell and batch scripts to reset privileged accounts across client environments.",
          "These scripts authenticate using service accounts with domain admin or equivalent privileges, bypassing modern identity governance platforms that require approval workflows and audit trails.",
          "An insider at the outsourcer is under quiet investigation for suspicious activity, including after-hours password resets and access to systems outside their normal scope.",
          "The scripts are stored in a shared network drive accessible to all helpdesk staff, and there's no version control or change monitoring.",
          "This is an outsourcing inheritance problem: you transferred operational control to a third party without ensuring they maintain the same security standards you'd apply internally, and now legacy tooling creates a privileged attack surface you can't directly control.",
        ],
        prompt: "How do you address the helpdesk privileged reset risk?",
        choices: [
          {
            id: "tighten-protocols",
            label: "Tighten reset protocols and monitoring immediately",
            summary: "Require approval workflows and audit trails for all privileged resets. Improves control adoption and reduces incident rate.",
            metricDeltas: { controlAdoption: 6, incidentRate: -4, welfareDebt: -3 },
          },
          {
            id: "insource-critical",
            label: "Insource critical reset operations and restrict vendor scope",
            summary: "Bring high-privilege resets in-house; vendor keeps low-privilege only. Strong control and debt improvement.",
            metricDeltas: { controlAdoption: 5, welfareDebt: -5, successIndex: 5, debtIndex: -2 },
          },
          {
            id: "audit-and-defer",
            label: "Audit and document; defer structural change",
            summary: "Document risk and defer changes. Small control gain; incident rate and debt stay elevated.",
            metricDeltas: { controlAdoption: 2, welfareDebt: 2, successIndex: -2 },
          },
        ],
      },
      {
        id: "round-1",
        title: "Vendor and insider investigation",
        messages: [
          "The insider investigation is ongoing. You can require the vendor to remove the individual from client access immediately, add real-time monitoring of all resets, or limit to read-only until the investigation completes.",
        ],
        prompt: "How do you respond to the insider risk?",
        choices: [
          {
            id: "remove-access",
            label: "Require vendor to remove individual from client access immediately",
            summary: "Immediate removal of access. Reduces incident rate and shows strong governance.",
            metricDeltas: { incidentRate: -4, welfareDebt: -3, successIndex: 4 },
          },
          {
            id: "realtime-monitoring",
            label: "Add real-time monitoring and alerting on all privileged resets",
            summary: "Monitor all resets in real time. Improves control adoption and reversibility.",
            metricDeltas: { controlAdoption: 5, systemReversibility: 3, successIndex: 3 },
          },
          {
            id: "read-only",
            label: "Limit vendor to read-only until investigation completes",
            summary: "Freeze privileged write access. Balanced; may impact operations.",
            metricDeltas: { controlAdoption: 3, incidentRate: -2, welfareDebt: -2 },
          },
        ],
      },
      {
        id: "round-2",
        title: "Long-term identity and outsourcing posture",
        messages: [
          "Leadership wants to align outsourced identity operations with FAIR-style loss exposure and control effectiveness.",
        ],
        prompt: "How do you strengthen identity and vendor posture?",
        choices: [
          {
            id: "identity-governance",
            label: "Deploy identity governance platform and vendor performance criteria",
            summary: "Unified identity governance and vendor SLAs. Strong control adoption and debt reduction.",
            metricDeltas: { controlAdoption: 7, welfareDebt: -6, successIndex: 5, debtIndex: -3 },
          },
          {
            id: "vendor-sla-only",
            label: "Tighten vendor SLAs and audit frequency only",
            summary: "Contractual and audit improvements. Moderate improvement.",
            metricDeltas: { controlAdoption: 4, welfareDebt: -3, successIndex: 3 },
          },
          {
            id: "accept-residual",
            label: "Accept residual risk and document for audit",
            summary: "Document and accept. Debt and incident rate remain higher.",
            metricDeltas: { welfareDebt: 2, debtIndex: 2 },
          },
        ],
      },
    ],
    resources: [
      {
        id: "outsourcing-security",
        label: "NIST Guidelines for Outsourcing Security Services",
        url: "https://csrc.nist.gov/publications/detail/sp/800-35/rev-1/final",
      },
    ],
  },
  {
    id: "sg-vendor-vpn",
    index: 5,
    title: "Vendor VPN hub with weak segmentation",
    shortTitle: "Vendor VPN hub",
    category: "Network · Vendor access",
    severity: "high",
    countryCode: "SG",
    countryName: "Singapore",
    latitude: 1.3521,
    longitude: 103.8198,
    company: {
      ...DEFAULT_COMPANY,
      name: "Asia-Pacific Logistics Network",
      sector: "Logistics & supply chain",
      description:
        "A regional logistics provider operating across Southeast Asia, managing vendor access networks for multiple clients. Revenue of $420M with 12% EBITDA margin. The company operates shared VPN infrastructure where multiple vendor partners connect to access client systems. Network segmentation relies on static firewall rules that were configured years ago and have accumulated technical debt. Vendor onboarding is handled by different teams over time, leading to inconsistent security policies and overlapping access rights.",
      annualRevenueMillions: 420,
      ebitdaMarginPercent: 12,
      region: "Southeast Asia",
      headquarters: "Singapore",
      employeeCount: 2100,
      foundedYear: 1998,
      infrastructure:
        "Shared vendor VPN hub (IPsec), legacy firewall rule base, multi-tenant client DMZs, cloud-based TMS and WMS",
      history:
        "Founded in Singapore in 1998; expanded across ASEAN through partnerships. Vendor access model grew organically; current VPN architecture dates to mid-2000s consolidation.",
    },
    lossProfile: {
      ...DEFAULT_LOSS,
      grossP90Millions: 85,
      netP90Millions: 28,
      meanLossMillions: 15,
      frequencyPerYear: 0.6,
      topDriver: "Vendor VPN hub enabling lateral movement between client environments",
    },
    metrics: {
      controlAdoption: 55,
      incidentRate: 24,
      successIndex: 44,
      welfareDebt: 82,
      systemReversibility: 22,
      debtIndex: 23,
    },
    fairFocus: "Vendor access and segmentation; LEF and control adoption.",
    steps: [
      {
        id: "intro",
        title: "Shared vendor VPN hub",
        messages: [
          "Asia-Pacific Logistics runs a shared vendor VPN hub where dozens of partners connect to access client staging and production systems.",
          "Segmentation relies on a legacy firewall rule base that has grown over 15 years. Many rules reference obsolete IP ranges or applications; ownership is scattered across teams that no longer exist.",
          "A recent audit found that several vendor accounts can reach multiple client environments from the same hub session because of overly permissive 'temporary' rules that were never removed.",
          "Multiple vendors effectively land in the same VPN hub, then pivot into production networks via static firewall rules that nobody fully owns anymore. This is a classic inheritance and accumulation problem.",
        ],
        prompt: "How do you address the vendor VPN segmentation risk?",
        choices: [
          {
            id: "rule-cleanup",
            label: "Immediate firewall rule cleanup and vendor segmentation review",
            summary: "Audit and remove obsolete rules; enforce one vendor per segment. Reduces incident rate and governance debt.",
            metricDeltas: { controlAdoption: 5, incidentRate: -4, welfareDebt: -4, successIndex: 4 },
          },
          {
            id: "zero-trust-pilot",
            label: "Pilot zero-trust vendor access for highest-risk clients",
            summary: "Implement least-privilege vendor access for top clients. Strong control and reversibility.",
            metricDeltas: { controlAdoption: 6, systemReversibility: 4, welfareDebt: -5, debtIndex: -2 },
          },
          {
            id: "document-and-defer",
            label: "Document risk and defer cleanup to next budget cycle",
            summary: "Document and accept until next cycle. Debt and incident rate stay elevated.",
            metricDeltas: { welfareDebt: 3, debtIndex: 3, successIndex: -3 },
          },
        ],
      },
      {
        id: "round-1",
        title: "Incident response and containment",
        messages: [
          "A vendor account was used to access a client environment inappropriately. You can revoke the vendor, isolate affected client segments, or add monitoring and restrict scope.",
        ],
        prompt: "How do you contain and respond?",
        choices: [
          {
            id: "revoke-vendor",
            label: "Revoke vendor access and require re-onboarding with new controls",
            summary: "Full revocation and re-onboarding. Strong signal; reduces incident rate and debt.",
            metricDeltas: { incidentRate: -5, welfareDebt: -4, controlAdoption: 3, successIndex: 4 },
          },
          {
            id: "isolate-segments",
            label: "Isolate affected client segments and add monitoring",
            summary: "Contain spread and monitor. Balanced impact.",
            metricDeltas: { incidentRate: -3, welfareDebt: -2, controlAdoption: 4 },
          },
          {
            id: "monitor-restrict",
            label: "Restrict scope and add monitoring; no revocation",
            summary: "Narrow access and monitor. Moderate improvement.",
            metricDeltas: { controlAdoption: 3, incidentRate: -2, welfareDebt: -1 },
          },
        ],
      },
      {
        id: "round-2",
        title: "Long-term vendor access architecture",
        messages: [
          "Leadership wants a sustainable vendor access model that keeps FAIR loss exposure within appetite.",
        ],
        prompt: "How do you strengthen vendor access long term?",
        choices: [
          {
            id: "zero-trust-full",
            label: "Roll out zero-trust vendor access and quarterly rule reviews",
            summary: "Full zero-trust and regular cleanup. Strong control adoption and debt reduction.",
            metricDeltas: { controlAdoption: 8, welfareDebt: -6, systemReversibility: 5, successIndex: 6 },
          },
          {
            id: "segment-and-review",
            label: "Strict segmentation and annual rule reviews",
            summary: "Enforce segmentation and annual reviews. Moderate improvement.",
            metricDeltas: { controlAdoption: 5, welfareDebt: -4, successIndex: 4 },
          },
          {
            id: "accept-residual",
            label: "Accept residual risk with enhanced monitoring",
            summary: "Monitor and document. Debt remains higher.",
            metricDeltas: { controlAdoption: 2, welfareDebt: 2, debtIndex: 2 },
          },
        ],
      },
    ],
  },
  {
    id: "br-cloud-cost-leak",
    index: 6,
    title: "Cloud misconfiguration leaking cost and data",
    shortTitle: "Cloud misconfig",
    category: "Cloud",
    severity: "medium",
    countryCode: "BR",
    countryName: "Brazil",
    latitude: -23.5505,
    longitude: -46.6333,
    company: {
      ...DEFAULT_COMPANY,
      name: "BrasilFin Serviços Financeiros",
      sector: "Fintech & payments",
      description:
        "A Brazilian fintech offering digital payments, lending, and billing services. Revenue R$1.2B (~$240M USD) with 22% EBITDA margin. Heavily cloud-native on AWS with legacy billing exports to S3 for analytics and regulatory reporting.",
      annualRevenueMillions: 240,
      ebitdaMarginPercent: 22,
      region: "Brazil",
      headquarters: "São Paulo, Brazil",
      employeeCount: 1100,
      foundedYear: 2016,
      infrastructure:
        "AWS multi-account (prod, staging, analytics), S3/Glacier for exports and archives, legacy billing pipeline writing to public-facing buckets",
      history:
        "Launched in 2016 as a payments startup; expanded into lending and B2B billing. Cloud-first from inception; cost and access controls lagged rapid growth.",
    },
    lossProfile: {
      ...DEFAULT_LOSS,
      grossP90Millions: 72,
      netP90Millions: 24,
      meanLossMillions: 14,
      frequencyPerYear: 0.55,
      topDriver: "Public cloud bucket exposing billing and PII exports",
    },
    metrics: {
      controlAdoption: 63,
      incidentRate: 19,
      successIndex: 49,
      welfareDebt: 68,
      systemReversibility: 34,
      debtIndex: 16,
    },
    fairFocus: "Data exposure and loss magnitude (LM); P90 tail loss.",
    steps: [
      {
        id: "intro",
        title: "Public bucket with sensitive exports",
        messages: [
          "BrasilFin runs nightly exports from the core billing system into S3 for analytics and regulatory submissions.",
          "A storage bucket containing those exports was left world-readable when the analytics team stood up a new pipeline. Access logs were not enabled initially.",
          "There is evidence of automated scraping from IP ranges associated with data brokers. The exposure window may have been several months.",
          "This is a cloud misconfiguration inheritance problem: the bucket permission model was never revisited as the data classification of the exports increased.",
        ],
        prompt: "How do you respond to the exposed bucket?",
        choices: [
          {
            id: "lock-and-investigate",
            label: "Lock bucket, enable logging, and start forensic investigation",
            summary: "Immediate lock and investigation. Reduces incident rate and improves success index.",
            metricDeltas: { incidentRate: -4, welfareDebt: -3, successIndex: 5, controlAdoption: 3 },
          },
          {
            id: "remediate-pipeline",
            label: "Remediate pipeline to private buckets and enforce access reviews",
            summary: "Fix pipeline and add access reviews. Strong control and debt improvement.",
            metricDeltas: { controlAdoption: 6, welfareDebt: -5, systemReversibility: 3, debtIndex: -2 },
          },
          {
            id: "document-and-notify",
            label: "Document exposure, notify if required, defer pipeline change",
            summary: "Comply with notification; defer structural change. Debt stays elevated.",
            metricDeltas: { successIndex: 2, welfareDebt: 2, debtIndex: 2 },
          },
        ],
      },
      {
        id: "round-1",
        title: "Data classification and retention",
        messages: [
          "Forensics shows billing and PII were exposed. You can classify all exports, reduce retention in S3, or add DLP and keep current retention.",
        ],
        prompt: "How do you reduce data exposure going forward?",
        choices: [
          {
            id: "classify-all",
            label: "Classify all exports and restrict buckets by classification",
            summary: "Full classification and bucket policy. Strong control adoption.",
            metricDeltas: { controlAdoption: 6, welfareDebt: -4, successIndex: 4 },
          },
          {
            id: "reduce-retention",
            label: "Reduce retention and move cold data to restricted Glacier",
            summary: "Shorter retention and restricted cold storage. Good balance.",
            metricDeltas: { controlAdoption: 4, incidentRate: -2, welfareDebt: -3 },
          },
          {
            id: "dlp-only",
            label: "Add DLP and monitoring; keep current retention",
            summary: "DLP and monitoring only. Moderate improvement.",
            metricDeltas: { controlAdoption: 3, incidentRate: -1, welfareDebt: -1 },
          },
        ],
      },
      {
        id: "round-2",
        title: "Cloud security posture long term",
        messages: [
          "Leadership wants cloud storage and pipelines aligned with FAIR loss exposure and control effectiveness.",
        ],
        prompt: "How do you strengthen cloud posture?",
        choices: [
          {
            id: "cspm-and-policy",
            label: "Deploy CSPM and enforce bucket policy as code",
            summary: "CSPM and policy-as-code. Strong control and reversibility.",
            metricDeltas: { controlAdoption: 7, systemReversibility: 5, welfareDebt: -5, debtIndex: -3 },
          },
          {
            id: "quarterly-reviews",
            label: "Quarterly access and bucket reviews only",
            summary: "Regular reviews. Moderate improvement.",
            metricDeltas: { controlAdoption: 4, welfareDebt: -3, successIndex: 3 },
          },
          {
            id: "accept-residual",
            label: "Accept residual risk and document for audit",
            summary: "Document and accept. Debt remains.",
            metricDeltas: { welfareDebt: 2, debtIndex: 2 },
          },
        ],
      },
    ],
  },
  {
    id: "za-backup-gap",
    index: 7,
    title: "Backups that cannot be restored in time",
    shortTitle: "Backup gap",
    category: "Resilience",
    severity: "high",
    countryCode: "ZA",
    countryName: "South Africa",
    latitude: -26.2041,
    longitude: 28.0473,
    company: {
      ...DEFAULT_COMPANY,
      name: "Southern African Financial Services",
      sector: "Regional banking",
      description:
        "A regional bank operating across South Africa and neighboring countries, providing retail and commercial banking services. Revenue of ZAR 2.8B (~$150M USD) with 25% EBITDA margin. Core banking systems run on legacy platforms with backup infrastructure that hasn't been fully tested for recovery scenarios. The bank operates multiple data centers with replication, but recovery time objectives (RTOs) are based on assumptions from years ago and haven't been validated under realistic failure conditions.",
      annualRevenueMillions: 150,
      ebitdaMarginPercent: 25,
      region: "Southern Africa",
      headquarters: "Johannesburg, South Africa",
      employeeCount: 2800,
      foundedYear: 1982,
      infrastructure:
        "Dual data centers (Johannesburg, Cape Town), legacy core banking (mainframe), backup to tape and replicated storage; RTO/RPO not recently validated",
      history:
        "Formed from a merger of two regional banks in 1982. Current backup and DR design dates to the early 2010s; full recovery tests have been deferred repeatedly.",
    },
    lossProfile: {
      ...DEFAULT_LOSS,
      grossP90Millions: 55,
      netP90Millions: 18,
      meanLossMillions: 10,
      frequencyPerYear: 0.3,
      topDriver: "Backup and recovery gaps creating extended downtime risk",
    },
    metrics: {
      controlAdoption: 57,
      incidentRate: 15,
      successIndex: 42,
      welfareDebt: 85,
      systemReversibility: 18,
      debtIndex: 26,
    },
    fairFocus: "Recovery and secondary loss; LEF and LM from extended downtime.",
    steps: [
      {
        id: "intro",
        title: "Backups as theatre",
        messages: [
          "Southern African Financial Services runs backups nightly; dashboards are green and capacity is monitored.",
          "No one has run a full recovery test within the business RTO in over four years. The last test exceeded RTO by a factor of three and was never fully remediated.",
          "A regional data center just degraded. Failover was initiated, but restore of critical databases from backup is now in progress and already past the stated RTO.",
          "Backups as theatre: they run and report success, but the ability to restore in time has not been validated. This is a resilience inheritance problem.",
        ],
        prompt: "How do you address the backup and recovery gap?",
        choices: [
          {
            id: "full-recovery-test",
            label: "Run full recovery test and fix gaps before next incident",
            summary: "Validate RTO and fix failures. Improves reversibility and success index.",
            metricDeltas: { systemReversibility: 6, successIndex: 5, welfareDebt: -4 },
          },
          {
            id: "incremental-test",
            label: "Incremental recovery tests and document current RTO",
            summary: "Test in phases and document actual RTO. Balanced impact.",
            metricDeltas: { systemReversibility: 4, successIndex: 3, welfareDebt: -2 },
          },
          {
            id: "document-and-defer",
            label: "Document gap and defer full test to next quarter",
            summary: "Document and defer. Debt and reversibility stay weak.",
            metricDeltas: { welfareDebt: 3, debtIndex: 3, successIndex: -2 },
          },
        ],
      },
      {
        id: "round-1",
        title: "During the current outage",
        messages: [
          "Restore is still in progress and has exceeded RTO. You can continue with current restore, fail over to DR with partial data, or declare a major incident and escalate.",
        ],
        prompt: "How do you respond during the outage?",
        choices: [
          {
            id: "continue-restore",
            label: "Continue current restore and communicate revised RTO",
            summary: "Complete restore and set realistic expectations. Improves success index.",
            metricDeltas: { successIndex: 4, incidentRate: -2, welfareDebt: -2 },
          },
          {
            id: "failover-dr",
            label: "Fail over to DR with partial data and accept data loss",
            summary: "DR failover; accept some data loss. Contains incident; reversibility still at risk.",
            metricDeltas: { incidentRate: -4, welfareDebt: -3, systemReversibility: -2 },
          },
          {
            id: "major-incident",
            label: "Declare major incident and escalate to board",
            summary: "Full escalation. Strong governance signal; debt and success improve.",
            metricDeltas: { successIndex: 5, welfareDebt: -4, controlAdoption: 2 },
          },
        ],
      },
      {
        id: "round-2",
        title: "Long-term resilience posture",
        messages: [
          "Leadership wants backup and recovery aligned with FAIR loss exposure and business continuity requirements.",
        ],
        prompt: "How do you strengthen resilience long term?",
        choices: [
          {
            id: "quarterly-rto",
            label: "Quarterly recovery tests and RTO validation",
            summary: "Regular tests and validated RTOs. Strong reversibility and debt reduction.",
            metricDeltas: { systemReversibility: 7, welfareDebt: -6, successIndex: 6, debtIndex: -3 },
          },
          {
            id: "annual-test",
            label: "Annual full test and updated runbooks",
            summary: "Annual test and runbooks. Moderate improvement.",
            metricDeltas: { systemReversibility: 4, welfareDebt: -3, successIndex: 3 },
          },
          {
            id: "accept-residual",
            label: "Accept residual recovery risk and document",
            summary: "Document and accept. Debt remains higher.",
            metricDeltas: { welfareDebt: 2, debtIndex: 2 },
          },
        ],
      },
    ],
  },
  {
    id: "au-shadow-it",
    index: 8,
    title: "Shadow IT analytics cluster with prod data",
    shortTitle: "Shadow analytics",
    category: "Shadow IT",
    severity: "medium",
    countryCode: "AU",
    countryName: "Australia",
    latitude: -33.8688,
    longitude: 151.2093,
    company: {
      ...DEFAULT_COMPANY,
      name: "Meridian Data & Analytics",
      sector: "Retail & consumer analytics",
      description:
        "An Australian retailer and loyalty platform with a large data science function. Revenue A$890M with 18% EBITDA margin. Production data is tightly controlled, but analytics teams have repeatedly built shadow environments to speed up experimentation.",
      annualRevenueMillions: 580,
      ebitdaMarginPercent: 18,
      region: "Australia & NZ",
      headquarters: "Sydney, Australia",
      employeeCount: 3200,
      foundedYear: 2005,
      infrastructure:
        "Production data warehouse (Snowflake), approved analytics sandboxes; unmanaged Spark/Databricks clusters with production data copies",
      history:
        "Grew from a loyalty-program startup; data science became central to personalization. Shadow analytics clusters emerged when governance couldn't keep pace with demand for data access.",
    },
    lossProfile: {
      ...DEFAULT_LOSS,
      grossP90Millions: 68,
      netP90Millions: 22,
      meanLossMillions: 12,
      frequencyPerYear: 0.5,
      topDriver: "Shadow analytics cluster holding production PII with weak access controls",
    },
    metrics: {
      controlAdoption: 68,
      incidentRate: 17,
      successIndex: 51,
      welfareDebt: 69,
      systemReversibility: 32,
      debtIndex: 19,
    },
    fairFocus: "Data exposure and P90 tail loss; control adoption and LEF.",
    steps: [
      {
        id: "intro",
        title: "Unauthorized analytics copy of production",
        messages: [
          "Meridian's data science team needed faster iteration on customer models. Approved sandboxes had strict size and refresh limits.",
          "A team cloned core production customer and transaction tables into an unmanaged analytics cluster (Databricks) in a separate subscription, arguing it was 'just for exploration'.",
          "The cluster has weak access controls, no DLP, and is not in scope for the main security monitoring. It holds PII and payment-related attributes.",
          "Shadow IT with production data: speed and convenience created a parallel perimeter that the organization does not fully control.",
        ],
        prompt: "How do you address the shadow analytics cluster?",
        choices: [
          {
            id: "shut-and-migrate",
            label: "Shut down cluster and migrate workloads to approved sandbox",
            summary: "Eliminate shadow environment. Strong control adoption and debt reduction.",
            metricDeltas: { controlAdoption: 6, welfareDebt: -5, successIndex: 4, incidentRate: -2 },
          },
          {
            id: "bring-under-governance",
            label: "Bring under governance with access controls and DLP",
            summary: "Govern in place. Balanced control and reversibility.",
            metricDeltas: { controlAdoption: 5, systemReversibility: 3, welfareDebt: -3 },
          },
          {
            id: "document-and-monitor",
            label: "Document risk and add monitoring; defer migration",
            summary: "Monitor and document. Debt stays elevated.",
            metricDeltas: { controlAdoption: 2, welfareDebt: 2, debtIndex: 2 },
          },
        ],
      },
      {
        id: "round-1",
        title: "Data exposure assessment",
        messages: [
          "Assessment shows PII and payment attributes in the cluster. You can de-identify in place, purge and restrict, or accept and encrypt.",
        ],
        prompt: "How do you reduce data exposure?",
        choices: [
          {
            id: "deidentify",
            label: "De-identify data in place and restrict access",
            summary: "De-identify and restrict. Reduces incident impact and improves control.",
            metricDeltas: { controlAdoption: 4, incidentRate: -3, welfareDebt: -3 },
          },
          {
            id: "purge-restrict",
            label: "Purge PII and restrict to aggregated data only",
            summary: "Remove PII; aggregated only. Strong control and debt improvement.",
            metricDeltas: { controlAdoption: 5, welfareDebt: -4, successIndex: 4 },
          },
          {
            id: "encrypt-only",
            label: "Encrypt at rest and add monitoring",
            summary: "Encrypt and monitor. Moderate improvement.",
            metricDeltas: { controlAdoption: 3, incidentRate: -1, welfareDebt: -1 },
          },
        ],
      },
      {
        id: "round-2",
        title: "Data and analytics governance long term",
        messages: [
          "Leadership wants analytics and data science aligned with FAIR loss exposure and control effectiveness.",
        ],
        prompt: "How do you strengthen data governance?",
        choices: [
          {
            id: "catalog-and-policy",
            label: "Data catalog, classification, and policy-based access",
            summary: "Catalog and policy. Strong control and reversibility.",
            metricDeltas: { controlAdoption: 7, systemReversibility: 5, welfareDebt: -5, debtIndex: -3 },
          },
          {
            id: "sandbox-only",
            label: "Strict sandbox-only policy and quarterly reviews",
            summary: "Sandbox-only and reviews. Moderate improvement.",
            metricDeltas: { controlAdoption: 5, welfareDebt: -3, successIndex: 3 },
          },
          {
            id: "accept-residual",
            label: "Accept residual risk with enhanced monitoring",
            summary: "Monitor and document. Debt remains.",
            metricDeltas: { welfareDebt: 2, debtIndex: 2 },
          },
        ],
      },
    ],
  },
  {
    id: "jp-legacy-authz",
    index: 9,
    title: "Legacy authorization layer nobody owns",
    shortTitle: "Authz inheritance",
    category: "Identity & access",
    severity: "medium",
    countryCode: "JP",
    countryName: "Japan",
    latitude: 35.6762,
    longitude: 139.6503,
    company: {
      ...DEFAULT_COMPANY,
      name: "Keisan Systems Corporation",
      sector: "Enterprise software & ERP",
      description:
        "A Japanese enterprise software vendor with large domestic and Asian deployments. Revenue ¥42B (~$280M USD) with 26% EBITDA margin. Authorization logic is spread across application layers, API gateways, and database roles built over decades.",
      annualRevenueMillions: 280,
      ebitdaMarginPercent: 26,
      region: "Japan & Asia-Pacific",
      headquarters: "Tokyo, Japan",
      employeeCount: 1850,
      foundedYear: 1978,
      infrastructure:
        "Legacy monoliths, microservice gateways, multiple DBs with role-based and row-level security; no unified authz model",
      history:
        "Founded in 1978; grew through product and acquisition. Authorization was implemented per-product and per-layer; consolidation never completed.",
    },
    lossProfile: {
      ...DEFAULT_LOSS,
      grossP90Millions: 58,
      netP90Millions: 20,
      meanLossMillions: 11,
      frequencyPerYear: 0.45,
      topDriver: "Inconsistent authorization across layers enabling privilege escalation",
    },
    metrics: {
      controlAdoption: 66,
      incidentRate: 14,
      successIndex: 53,
      welfareDebt: 71,
      systemReversibility: 27,
      debtIndex: 15,
    },
    fairFocus: "Privilege escalation and vulnerability (LEF).",
    steps: [
      {
        id: "intro",
        title: "Authorization scattered across layers",
        messages: [
          "Keisan's products enforce access control in application code, API gateways, and database views. Each layer was designed at different times by different teams.",
          "Over time, authorization decisions have drifted: some checks happen at the gateway, others only in the app, and some only in the database. Inconsistencies have been patched locally rather than redesigned.",
          "No one can confidently answer 'who can do what where' across the full stack. A recent internal audit found paths where gateway and DB disagreed, allowing unintended access.",
          "Legacy authorization inheritance: scattered ownership and no single model. This creates both compliance and security risk.",
        ],
        prompt: "How do you address the authorization fragmentation?",
        choices: [
          {
            id: "unified-model",
            label: "Design and implement a unified authorization model",
            summary: "Single model across gateway, app, and DB. Strong control adoption and reversibility.",
            metricDeltas: { controlAdoption: 6, systemReversibility: 5, welfareDebt: -5, successIndex: 4 },
          },
          {
            id: "audit-and-patch",
            label: "Audit all paths and patch inconsistencies",
            summary: "Find and fix inconsistencies. Moderate improvement; technical debt remains.",
            metricDeltas: { controlAdoption: 4, welfareDebt: -3, incidentRate: -2 },
          },
          {
            id: "document-and-defer",
            label: "Document gaps and defer unified model to roadmap",
            summary: "Document and defer. Debt and incident rate stay elevated.",
            metricDeltas: { welfareDebt: 3, debtIndex: 2, successIndex: -2 },
          },
        ],
      },
      {
        id: "round-1",
        title: "Incident and audit response",
        messages: [
          "The internal audit found paths where gateway and DB disagreed. You can fix critical paths first, add runtime checks, or document and prioritize for next quarter.",
        ],
        prompt: "How do you respond to the audit findings?",
        choices: [
          {
            id: "fix-critical",
            label: "Fix critical paths and add integration tests",
            summary: "Fix highest-risk paths and lock in with tests. Reduces incident rate and debt.",
            metricDeltas: { incidentRate: -4, welfareDebt: -4, controlAdoption: 3, successIndex: 4 },
          },
          {
            id: "runtime-checks",
            label: "Add runtime authorization checks and alerting",
            summary: "Detect and alert on mismatches. Improves control and reversibility.",
            metricDeltas: { controlAdoption: 4, systemReversibility: 3, successIndex: 3 },
          },
          {
            id: "document-prioritize",
            label: "Document and prioritize for next quarter",
            summary: "Document and defer. Debt remains.",
            metricDeltas: { welfareDebt: 2, debtIndex: 2 },
          },
        ],
      },
      {
        id: "round-2",
        title: "Long-term authorization posture",
        messages: [
          "Leadership wants authorization aligned with FAIR loss exposure and control effectiveness.",
        ],
        prompt: "How do you strengthen authorization long term?",
        choices: [
          {
            id: "centralized-policy",
            label: "Centralized policy engine and consistent enforcement",
            summary: "Single policy engine. Strong control and debt reduction.",
            metricDeltas: { controlAdoption: 7, welfareDebt: -6, systemReversibility: 5, debtIndex: -3 },
          },
          {
            id: "standardize-layers",
            label: "Standardize checks across gateway and app layers",
            summary: "Consistent checks across layers. Moderate improvement.",
            metricDeltas: { controlAdoption: 5, welfareDebt: -3, successIndex: 3 },
          },
          {
            id: "accept-residual",
            label: "Accept residual risk with enhanced monitoring",
            summary: "Monitor and document. Debt remains.",
            metricDeltas: { welfareDebt: 2, debtIndex: 2 },
          },
        ],
      },
    ],
  },
  {
    id: "se-logging-gap",
    index: 10,
    title: "Critical paths without end‑to‑end logging",
    shortTitle: "Logging gap",
    category: "Detection & response",
    severity: "medium",
    countryCode: "SE",
    countryName: "Sweden",
    latitude: 59.3293,
    longitude: 18.0686,
    company: {
      ...DEFAULT_COMPANY,
      name: "Nordic Payments AB",
      sector: "Payments & card processing",
      description:
        "A Nordic card processor and payment gateway. Revenue SEK 1.8B (~$170M USD) with 28% EBITDA margin. Critical transaction paths span multiple systems and partners; logging is per-system with no unified view.",
      annualRevenueMillions: 170,
      ebitdaMarginPercent: 28,
      region: "Nordics",
      headquarters: "Stockholm, Sweden",
      employeeCount: 950,
      foundedYear: 1992,
      infrastructure:
        "Card switching, issuer/acquirer links, fraud engines, partner APIs; logs in Splunk, CloudWatch, and legacy syslog with no single correlation",
      history:
        "Emerged from a bank consortium in 1992; added gateway and open banking. Logging grew system-by-system; end-to-end visibility was never fully implemented.",
    },
    lossProfile: {
      ...DEFAULT_LOSS,
      grossP90Millions: 48,
      netP90Millions: 16,
      meanLossMillions: 9,
      frequencyPerYear: 0.4,
      topDriver: "Fragmented logging delaying detection and response to transaction fraud",
    },
    metrics: {
      controlAdoption: 70,
      incidentRate: 12,
      successIndex: 55,
      welfareDebt: 60,
      systemReversibility: 35,
      debtIndex: 12,
    },
    steps: [
      {
        id: "intro",
        title: "No single view of critical transactions",
        messages: [
          "Nordic Payments routes key customer transactions across switching, fraud, and partner systems. Each component logs to its own store.",
          "There is no single view of a transaction from end to end. When something goes wrong, analysts must manually correlate across Splunk, CloudWatch, and legacy syslog.",
          "Anomalies are hard to detect or investigate quickly. A recent incident took days to trace because critical hops were not in the same log pipeline.",
          "Critical paths without end-to-end logging: detection and response are slowed by fragmentation. This is a visibility inheritance problem.",
        ],
        prompt: "How do you address the logging gap?",
        choices: [
          {
            id: "unified-pipeline",
            label: "Build unified transaction log pipeline and correlation",
            summary: "Single pipeline for critical path. Strong control and reversibility.",
            metricDeltas: { controlAdoption: 6, systemReversibility: 5, welfareDebt: -4, successIndex: 5 },
          },
          {
            id: "critical-path-only",
            label: "Instrument critical path only with end-to-end IDs",
            summary: "End-to-end IDs on critical path. Balanced improvement.",
            metricDeltas: { controlAdoption: 4, welfareDebt: -3, incidentRate: -2 },
          },
          {
            id: "document-and-defer",
            label: "Document gap and defer pipeline to next year",
            summary: "Document and defer. Debt stays elevated.",
            metricDeltas: { welfareDebt: 2, debtIndex: 2, successIndex: -2 },
          },
        ],
      },
      {
        id: "round-1",
        title: "During an active investigation",
        messages: [
          "A transaction anomaly is under investigation. You can add temporary correlation, escalate for manual correlation, or accept delayed resolution.",
        ],
        prompt: "How do you support the investigation?",
        choices: [
          {
            id: "temp-correlation",
            label: "Add temporary correlation and dashboards for this path",
            summary: "Quick win for this path. Improves success index and incident response.",
            metricDeltas: { successIndex: 4, incidentRate: -2, welfareDebt: -2 },
          },
          {
            id: "escalate-manual",
            label: "Escalate and commit to manual correlation this time",
            summary: "Manual effort now. Moderate success; debt remains.",
            metricDeltas: { successIndex: 2, welfareDebt: -1 },
          },
          {
            id: "accept-delayed",
            label: "Accept delayed resolution and document",
            summary: "Document and accept delay. Debt increases.",
            metricDeltas: { welfareDebt: 2, successIndex: -2 },
          },
        ],
      },
      {
        id: "round-2",
        title: "Long-term detection and response posture",
        messages: [
          "Leadership wants logging and detection aligned with FAIR loss exposure and response readiness.",
        ],
        prompt: "How do you strengthen detection long term?",
        choices: [
          {
            id: "soc-and-pipeline",
            label: "Unified pipeline and SOC playbooks for critical path",
            summary: "Pipeline and playbooks. Strong control and debt reduction.",
            metricDeltas: { controlAdoption: 7, welfareDebt: -5, successIndex: 6, debtIndex: -2 },
          },
          {
            id: "playbooks-only",
            label: "Playbooks and runbooks; incremental pipeline",
            summary: "Playbooks first; pipeline incremental. Moderate improvement.",
            metricDeltas: { controlAdoption: 4, welfareDebt: -3, successIndex: 3 },
          },
          {
            id: "accept-residual",
            label: "Accept residual visibility risk",
            summary: "Document and accept. Debt remains.",
            metricDeltas: { welfareDebt: 2, debtIndex: 2 },
          },
        ],
      },
    ],
  },
  {
    id: "ae-cross-border",
    index: 11,
    title: "Cross‑border data flows with unclear basis",
    shortTitle: "Cross‑border data",
    category: "Regulatory",
    severity: "medium",
    countryCode: "AE",
    countryName: "United Arab Emirates",
    latitude: 25.2048,
    longitude: 55.2708,
    company: {
      ...DEFAULT_COMPANY,
      name: "Gulf Digital Services FZCO",
      sector: "Digital services & cloud",
      description:
        "A UAE-headquartered digital services firm offering cloud, data analytics, and cross-border data flows for regional enterprises. Revenue AED 680M (~$185M USD) with 20% EBITDA margin. Data flows span UAE, EU, and other jurisdictions; legal and technical documentation are out of sync.",
      annualRevenueMillions: 185,
      ebitdaMarginPercent: 20,
      region: "GCC & MEA",
      headquarters: "Dubai, UAE",
      employeeCount: 1200,
      foundedYear: 2010,
      infrastructure:
        "Multi-region cloud (UAE, EU), data pipelines and analytics; cross-border transfers via API and batch; documentation incomplete",
      history:
        "Founded in Dubai in 2010; expanded services and geography. Data flow design evolved with deals; regulatory documentation and DPIAs lagged.",
    },
    lossProfile: {
      ...DEFAULT_LOSS,
      grossP90Millions: 52,
      netP90Millions: 18,
      meanLossMillions: 10,
      frequencyPerYear: 0.35,
      topDriver: "Cross-border data flows with unclear legal basis and outdated documentation",
    },
    metrics: {
      controlAdoption: 64,
      incidentRate: 11,
      successIndex: 49,
      welfareDebt: 74,
      systemReversibility: 26,
      debtIndex: 20,
    },
    fairFocus: "Compliance and secondary loss (LM); cross-border exposure.",
    steps: [
      {
        id: "intro",
        title: "Regulators asking hard questions",
        messages: [
          "Gulf Digital moves customer data between UAE, EU, and other regions for processing and analytics. Regulators are now reviewing how those flows are justified and protected.",
          "Documentation lags the reality of integrations and exports. Several pipelines were built under 'standard contractual clauses' that have since been challenged; others lack clear records.",
          "Regulators are asking hard questions: lawful basis, retention, and onward transfers. The team cannot quickly produce an accurate end-to-end map.",
          "Cross-border data flows with unclear basis: regulatory and technical inheritance. This creates compliance and reputational risk.",
        ],
        prompt: "How do you address the cross-border documentation gap?",
        choices: [
          {
            id: "full-mapping",
            label: "Full data flow mapping and DPIA refresh",
            summary: "Map all flows and refresh DPIAs. Strong control and debt reduction.",
            metricDeltas: { controlAdoption: 5, welfareDebt: -5, successIndex: 5, debtIndex: -2 },
          },
          {
            id: "critical-flows-only",
            label: "Map critical flows and document legal basis",
            summary: "Critical flows and basis. Balanced improvement.",
            metricDeltas: { controlAdoption: 3, welfareDebt: -3, successIndex: 3 },
          },
          {
            id: "document-and-defer",
            label: "Document gaps and defer full mapping",
            summary: "Document and defer. Debt stays elevated.",
            metricDeltas: { welfareDebt: 2, debtIndex: 2 },
          },
        ],
      },
      {
        id: "round-1",
        title: "Regulator request",
        messages: [
          "A regulator has requested a detailed explanation of specific data flows. You can produce a quick summary, commission a full audit, or request an extension.",
        ],
        prompt: "How do you respond to the regulator?",
        choices: [
          {
            id: "quick-summary",
            label: "Produce quick summary from existing docs and flag gaps",
            summary: "Transparent summary. Improves success index; some debt remains.",
            metricDeltas: { successIndex: 4, welfareDebt: -2 },
          },
          {
            id: "full-audit",
            label: "Commission full audit and correct documentation",
            summary: "Full audit and correction. Strong control and debt improvement.",
            metricDeltas: { controlAdoption: 5, welfareDebt: -5, successIndex: 5 },
          },
          {
            id: "extension",
            label: "Request extension and start mapping",
            summary: "Buy time and start work. Moderate improvement.",
            metricDeltas: { successIndex: 2, welfareDebt: -1 },
          },
        ],
      },
      {
        id: "round-2",
        title: "Long-term data governance posture",
        messages: [
          "Leadership wants cross-border flows aligned with regulatory and FAIR loss exposure.",
        ],
        prompt: "How do you strengthen data governance long term?",
        choices: [
          {
            id: "governance-program",
            label: "Data governance program and flow approval process",
            summary: "Governance program and approval. Strong control and debt reduction.",
            metricDeltas: { controlAdoption: 6, welfareDebt: -5, systemReversibility: 3, debtIndex: -3 },
          },
          {
            id: "annual-review",
            label: "Annual flow review and documentation",
            summary: "Annual review. Moderate improvement.",
            metricDeltas: { controlAdoption: 4, welfareDebt: -3, successIndex: 3 },
          },
          {
            id: "accept-residual",
            label: "Accept residual compliance risk",
            summary: "Document and accept. Debt remains.",
            metricDeltas: { welfareDebt: 2, debtIndex: 2 },
          },
        ],
      },
    ],
  },
  {
    id: "ca-end-of-life-os",
    index: 12,
    title: "End‑of‑life OS anchoring critical service",
    shortTitle: "EOL platform",
    category: "Platform risk",
    severity: "high",
    countryCode: "CA",
    countryName: "Canada",
    latitude: 51.0447,
    longitude: -114.0719,
    company: {
      ...DEFAULT_COMPANY,
      name: "Northern Energy Systems Inc.",
      sector: "Energy & utilities",
      description:
        "A Canadian energy company with generation, transmission, and customer systems. Revenue C$2.1B (~$1.5B USD) with 14% EBITDA margin. A revenue-critical billing and settlement workload runs on an end-of-life OS; migration has been deferred repeatedly.",
      annualRevenueMillions: 1500,
      ebitdaMarginPercent: 14,
      region: "Canada",
      headquarters: "Calgary, Canada",
      employeeCount: 4200,
      foundedYear: 1968,
      infrastructure:
        "SCADA, billing and settlement (legacy Unix), customer portals (cloud); critical workload on unsupported OS with no security patches",
      history:
        "Legacy billing/settlement system dates to the 1990s; OS went end-of-life. Migration plans have slipped due to cost and risk; 'it still works' has prevailed.",
    },
    lossProfile: {
      ...DEFAULT_LOSS,
      grossP90Millions: 95,
      netP90Millions: 32,
      meanLossMillions: 22,
      frequencyPerYear: 0.5,
      topDriver: "Revenue-critical workload on unsupported OS with no security patches",
    },
    metrics: {
      controlAdoption: 59,
      incidentRate: 21,
      successIndex: 41,
      welfareDebt: 83,
      systemReversibility: 19,
      debtIndex: 24,
    },
    fairFocus: "Vulnerability and LEF; unpatched and unsupported systems.",
    steps: [
      {
        id: "intro",
        title: "Critical workload on unsupported OS",
        messages: [
          "Northern Energy's billing and settlement system is revenue-critical. It runs on an OS that has been out of support for years.",
          "The migration plan keeps slipping because 'it still works' and the business case for migration competes with other priorities. Security patches are no longer available.",
          "Regulators and auditors have started asking about end-of-life systems. A single major incident could force an emergency migration under crisis conditions.",
          "End-of-life OS anchoring critical service: technical debt has become a strategic and security risk.",
        ],
        prompt: "How do you address the end-of-life OS risk?",
        choices: [
          {
            id: "migrate-now",
            label: "Accelerate migration with dedicated program",
            summary: "Full migration program. Strong reversibility and debt reduction; cost and risk in short term.",
            metricDeltas: { systemReversibility: 7, welfareDebt: -6, successIndex: 5, controlAdoption: 3 },
          },
          {
            id: "isolate-and-harden",
            label: "Isolate and harden in place while planning migration",
            summary: "Network isolation and hardening; migration in plan. Balanced impact.",
            metricDeltas: { controlAdoption: 5, incidentRate: -3, welfareDebt: -3, successIndex: 3 },
          },
          {
            id: "document-and-defer",
            label: "Document risk and defer migration again",
            summary: "Document and defer. Debt and incident rate stay high.",
            metricDeltas: { welfareDebt: 4, debtIndex: 4, successIndex: -3 },
          },
        ],
      },
      {
        id: "round-1",
        title: "Vulnerability disclosure",
        messages: [
          "A critical vulnerability affecting the end-of-life OS was disclosed. No patch is available. You can isolate the system, accept risk with compensating controls, or accelerate migration.",
        ],
        prompt: "How do you respond?",
        choices: [
          {
            id: "isolate-now",
            label: "Isolate system from network and accelerate migration",
            summary: "Immediate isolation and migration. Strong incident and debt reduction.",
            metricDeltas: { incidentRate: -5, welfareDebt: -4, successIndex: 5 },
          },
          {
            id: "compensating",
            label: "Add compensating controls and monitor closely",
            summary: "Compensating controls. Moderate improvement.",
            metricDeltas: { controlAdoption: 3, incidentRate: -2, welfareDebt: -2 },
          },
          {
            id: "accept-risk",
            label: "Accept risk and document for insurance",
            summary: "Document and accept. Debt increases.",
            metricDeltas: { welfareDebt: 3, debtIndex: 3 },
          },
        ],
      },
      {
        id: "round-2",
        title: "Long-term platform posture",
        messages: [
          "Leadership wants critical platforms aligned with support and FAIR loss exposure.",
        ],
        prompt: "How do you strengthen platform posture long term?",
        choices: [
          {
            id: "lifecycle-policy",
            label: "Platform lifecycle policy and mandatory refresh",
            summary: "Lifecycle policy and refresh. Strong control and debt reduction.",
            metricDeltas: { controlAdoption: 6, welfareDebt: -5, systemReversibility: 5, debtIndex: -3 },
          },
          {
            id: "critical-only",
            label: "Lifecycle for critical systems only",
            summary: "Critical systems only. Moderate improvement.",
            metricDeltas: { controlAdoption: 4, welfareDebt: -3, successIndex: 3 },
          },
          {
            id: "accept-residual",
            label: "Accept residual platform risk",
            summary: "Document and accept. Debt remains.",
            metricDeltas: { welfareDebt: 2, debtIndex: 2 },
          },
        ],
      },
    ],
  },
  {
    id: "mx-identity-federation",
    index: 13,
    title: "Complex identity federation chain",
    shortTitle: "Identity federation",
    category: "Identity & access",
    severity: "medium",
    countryCode: "MX",
    countryName: "Mexico",
    latitude: 25.6866,
    longitude: -100.3161,
    company: {
      ...DEFAULT_COMPANY,
      name: "Banco Comercial del Norte S.A.",
      sector: "Banking & financial services",
      description:
        "A Mexican commercial bank with corporate and retail operations. Revenue MXN 28B (~$1.4B USD) with 24% EBITDA margin. Identity federation chains across internal IdP, B2B partners, and legacy SAML bridges with inconsistent security postures.",
      annualRevenueMillions: 1400,
      ebitdaMarginPercent: 24,
      region: "Mexico",
      headquarters: "Monterrey, Mexico",
      employeeCount: 8500,
      foundedYear: 1954,
      infrastructure:
        "Core banking, corporate portal, B2B SSO; federation across Azure AD, partner IdPs, and legacy SAML; misconfigurations have caused outages",
      history:
        "Federation was added incrementally for partners and acquisitions. Each hop was designed in isolation; end-to-end trust and failure modes were never fully modeled.",
    },
    lossProfile: {
      ...DEFAULT_LOSS,
      grossP90Millions: 78,
      netP90Millions: 26,
      meanLossMillions: 15,
      frequencyPerYear: 0.5,
      topDriver: "Complex identity federation chain with fragile trust and misconfiguration risk",
    },
    metrics: {
      controlAdoption: 67,
      incidentRate: 13,
      successIndex: 50,
      welfareDebt: 69,
      systemReversibility: 31,
      debtIndex: 18,
    },
    fairFocus: "Identity and trust boundaries; vulnerability and LEF.",
    steps: [
      {
        id: "intro",
        title: "Too many hops to trust",
        messages: [
          "Banco Comercial del Norte authenticates users through a chain: internal IdP, then B2B partner IdPs, and legacy SAML bridges for acquired systems.",
          "Authentication now chains across multiple identity providers, B2B links, and legacy SAML bridges. Small misconfigurations have caused outages and access issues.",
          "Trust boundaries and failure modes were never fully documented. A recent partner certificate rollover broke access for a segment of corporate clients.",
          "Too many hops to trust: complex identity federation is an inheritance and operational risk.",
        ],
        prompt: "How do you address the federation chain risk?",
        choices: [
          {
            id: "simplify-chain",
            label: "Simplify chain and consolidate to fewer trusted hops",
            summary: "Reduce hops and consolidate. Strong control and reversibility.",
            metricDeltas: { controlAdoption: 6, systemReversibility: 5, welfareDebt: -5, successIndex: 4 },
          },
          {
            id: "document-and-monitor",
            label: "Document trust boundaries and add monitoring",
            summary: "Document and monitor. Balanced improvement.",
            metricDeltas: { controlAdoption: 4, welfareDebt: -3, incidentRate: -2 },
          },
          {
            id: "accept-residual",
            label: "Accept residual risk and document",
            summary: "Document and accept. Debt stays elevated.",
            metricDeltas: { welfareDebt: 3, debtIndex: 2 },
          },
        ],
      },
      {
        id: "round-1",
        title: "Outage and certificate rollover",
        messages: [
          "A partner certificate rollover broke access for a segment of corporate clients. You can fix the immediate issue only, fix and document failure modes, or add redundancy.",
        ],
        prompt: "How do you respond?",
        choices: [
          {
            id: "fix-only",
            label: "Fix immediate issue and restore access",
            summary: "Restore access. Minimal debt improvement.",
            metricDeltas: { successIndex: 2, incidentRate: -1 },
          },
          {
            id: "fix-and-document",
            label: "Fix and document failure modes and runbooks",
            summary: "Fix and document. Improves success and debt.",
            metricDeltas: { successIndex: 4, welfareDebt: -3, controlAdoption: 2 },
          },
          {
            id: "add-redundancy",
            label: "Add redundancy and automated rollover testing",
            summary: "Redundancy and testing. Strong control and reversibility.",
            metricDeltas: { controlAdoption: 5, systemReversibility: 4, welfareDebt: -4 },
          },
        ],
      },
      {
        id: "round-2",
        title: "Long-term federation posture",
        messages: [
          "Leadership wants identity federation aligned with FAIR loss exposure and availability.",
        ],
        prompt: "How do you strengthen federation long term?",
        choices: [
          {
            id: "unified-trust",
            label: "Unified trust model and partner security requirements",
            summary: "Unified model and partner requirements. Strong control and debt reduction.",
            metricDeltas: { controlAdoption: 7, welfareDebt: -6, successIndex: 5, debtIndex: -3 },
          },
          {
            id: "partner-audits",
            label: "Regular partner audits and certificate lifecycle",
            summary: "Audits and lifecycle. Moderate improvement.",
            metricDeltas: { controlAdoption: 4, welfareDebt: -3, successIndex: 3 },
          },
          {
            id: "accept-residual",
            label: "Accept residual federation risk",
            summary: "Document and accept. Debt remains.",
            metricDeltas: { welfareDebt: 2, debtIndex: 2 },
          },
        ],
      },
    ],
  },
  {
    id: "ng-mobile-money",
    index: 14,
    title: "Mobile money platform with weak segregation",
    shortTitle: "Mobile money",
    category: "Payments",
    severity: "high",
    countryCode: "NG",
    countryName: "Nigeria",
    latitude: 6.5244,
    longitude: 3.3792,
    company: {
      ...DEFAULT_COMPANY,
      name: "PagaWave Mobile Money Ltd",
      sector: "Mobile money & payments",
      description:
        "A Nigerian mobile money and agency platform with rapid growth. Revenue NGN 48B (~$60M USD) with 28% EBITDA margin. Payment rails span consumer apps, agent networks, and core banking with uneven controls and segregation between zones.",
      annualRevenueMillions: 60,
      ebitdaMarginPercent: 28,
      region: "West Africa",
      headquarters: "Lagos, Nigeria",
      employeeCount: 650,
      foundedYear: 2012,
      infrastructure:
        "Mobile apps, agent management, core banking integration; trust zones between consumer, agent, and core with inconsistent controls",
      history:
        "Launched in 2012; scaled quickly. Security and segregation were bolted on; payment rails cross trust zones with weak segregation in places.",
    },
    lossProfile: {
      ...DEFAULT_LOSS,
      grossP90Millions: 42,
      netP90Millions: 14,
      meanLossMillions: 8,
      frequencyPerYear: 0.6,
      topDriver: "Payment rails crossing trust zones with weak segregation and agent risk",
    },
    metrics: {
      controlAdoption: 54,
      incidentRate: 23,
      successIndex: 43,
      welfareDebt: 86,
      systemReversibility: 21,
      debtIndex: 27,
    },
    fairFocus: "Trust boundaries and loss magnitude (LM); payment and agent risk.",
    steps: [
      {
        id: "intro",
        title: "Payment rails crossing trust zones",
        messages: [
          "PagaWave's mobile money platform spans consumer devices, agent networks, and core banking. Growth has been rapid; controls were not uniform across zones.",
          "Payment rails cross trust zones: consumer-to-agent, agent-to-core, and partner integrations. Segregation is uneven; some paths have weak authentication or logging.",
          "A fast-growing mobile money platform with weak segregation: agent compromise or partner misuse could propagate. Regulators are focusing on agent and operational risk.",
          "Payment rails crossing trust zones with uneven controls: this is a scale and inheritance problem in a high-growth environment.",
        ],
        prompt: "How do you address the payment rail segregation risk?",
        choices: [
          {
            id: "strict-segregation",
            label: "Strict segregation between consumer, agent, and core",
            summary: "Enforce strict boundaries. Strong control and debt reduction.",
            metricDeltas: { controlAdoption: 6, welfareDebt: -5, incidentRate: -4, successIndex: 4 },
          },
          {
            id: "agent-hardening",
            label: "Agent hardening and transaction monitoring",
            summary: "Harden agent channel and monitor. Balanced improvement.",
            metricDeltas: { controlAdoption: 4, welfareDebt: -3, incidentRate: -2 },
          },
          {
            id: "document-and-defer",
            label: "Document risk and defer structural change",
            summary: "Document and defer. Debt stays elevated.",
            metricDeltas: { welfareDebt: 3, debtIndex: 3 },
          },
        ],
      },
      {
        id: "round-1",
        title: "Suspicious agent activity",
        messages: [
          "Suspicious activity was detected in an agent account. You can suspend the agent, add monitoring, or restrict to read-only until investigation completes.",
        ],
        prompt: "How do you respond?",
        choices: [
          {
            id: "suspend-agent",
            label: "Suspend agent and investigate",
            summary: "Immediate suspension. Reduces incident rate and debt.",
            metricDeltas: { incidentRate: -4, welfareDebt: -3, successIndex: 4 },
          },
          {
            id: "monitor-and-restrict",
            label: "Add monitoring and restrict transaction limits",
            summary: "Monitor and restrict. Balanced impact.",
            metricDeltas: { controlAdoption: 3, incidentRate: -2, welfareDebt: -2 },
          },
          {
            id: "read-only",
            label: "Restrict to read-only until investigation",
            summary: "Read-only. Moderate improvement.",
            metricDeltas: { controlAdoption: 2, incidentRate: -1 },
          },
        ],
      },
      {
        id: "round-2",
        title: "Long-term payment and agent posture",
        messages: [
          "Leadership wants payment rails aligned with FAIR loss exposure and regulatory focus on agent risk.",
        ],
        prompt: "How do you strengthen payment posture long term?",
        choices: [
          {
            id: "agent-program",
            label: "Formal agent risk program and segregation",
            summary: "Agent program and segregation. Strong control and debt reduction.",
            metricDeltas: { controlAdoption: 7, welfareDebt: -6, successIndex: 5, debtIndex: -3 },
          },
          {
            id: "monitoring-only",
            label: "Enhanced monitoring and agent audits",
            summary: "Monitoring and audits. Moderate improvement.",
            metricDeltas: { controlAdoption: 4, welfareDebt: -3, successIndex: 3 },
          },
          {
            id: "accept-residual",
            label: "Accept residual agent and rail risk",
            summary: "Document and accept. Debt remains.",
            metricDeltas: { welfareDebt: 2, debtIndex: 2 },
          },
        ],
      },
    ],
  },
  {
    id: "cn-supply-chain",
    index: 15,
    title: "Software supply‑chain risk in build systems",
    shortTitle: "Supply‑chain",
    category: "Software supply chain",
    severity: "high",
    countryCode: "CN",
    countryName: "China",
    latitude: 22.5431,
    longitude: 114.0579,
    company: {
      ...DEFAULT_COMPANY,
      name: "Pacific DevTools Technology Co.",
      sector: "Software development tools & DevOps",
      description:
        "A software tools and DevOps platform company with significant use of open source and third-party build dependencies. Revenue CNY 1.2B (~$170M USD) with 22% EBITDA margin. Build pipelines and supply chain are critical; a recent advisory highlighted a compromised dependency.",
      annualRevenueMillions: 170,
      ebitdaMarginPercent: 22,
      region: "Asia-Pacific",
      headquarters: "Shenzhen, China",
      employeeCount: 880,
      foundedYear: 2014,
      infrastructure:
        "CI/CD (Jenkins, GitLab), internal package registry, heavy use of public npm/pip; build pipeline as critical perimeter",
      history:
        "Founded in 2014; adopted open source and DevOps early. Supply chain security was not initially a focus; recent advisories have raised urgency.",
    },
    lossProfile: {
      ...DEFAULT_LOSS,
      grossP90Millions: 65,
      netP90Millions: 22,
      meanLossMillions: 14,
      frequencyPerYear: 0.55,
      topDriver: "Software supply chain compromise via build pipeline or third-party dependency",
    },
    metrics: {
      controlAdoption: 62,
      incidentRate: 25,
      successIndex: 45,
      welfareDebt: 78,
      systemReversibility: 29,
      debtIndex: 22,
    },
    fairFocus: "Supply chain and TEF; compromise propagation and LM.",
    steps: [
      {
        id: "intro",
        title: "Build pipeline as a new perimeter",
        messages: [
          "Pacific DevTools builds and ships software using third-party dependencies, internal packages, and CI systems. The build pipeline is a critical perimeter but was not designed with supply chain security as a first-class concern.",
          "A recent advisory highlights compromise of a widely used build or dependency tool that Pacific relies on heavily. Patching and verification are underway, but impact is still being assessed.",
          "Third-party dependencies, internal packages, and CI systems now form a critical perimeter. Small compromises can propagate to many products and customers.",
          "Software supply-chain risk in build systems: the new perimeter requires visibility, controls, and response that many organizations are still building.",
        ],
        prompt: "How do you address the supply chain risk?",
        choices: [
          {
            id: "lock-and-verify",
            label: "Lock dependencies and verify integrity",
            summary: "Lockfile and verification. Strong control and debt reduction.",
            metricDeltas: { controlAdoption: 6, welfareDebt: -5, incidentRate: -3, successIndex: 4 },
          },
          {
            id: "sbom-and-scan",
            label: "SBOM and vulnerability scanning in pipeline",
            summary: "SBOM and scanning. Balanced improvement.",
            metricDeltas: { controlAdoption: 5, welfareDebt: -3, systemReversibility: 2 },
          },
          {
            id: "document-and-defer",
            label: "Document risk and defer tooling",
            summary: "Document and defer. Debt stays elevated.",
            metricDeltas: { welfareDebt: 3, debtIndex: 2 },
          },
        ],
      },
      {
        id: "round-1",
        title: "Compromised dependency response",
        messages: [
          "A widely used dependency was reported compromised. You can patch and redeploy, quarantine and replace, or accept risk with monitoring.",
        ],
        prompt: "How do you respond?",
        choices: [
          {
            id: "patch-redeploy",
            label: "Patch and redeploy all affected artifacts",
            summary: "Full patch and redeploy. Strong incident and debt reduction.",
            metricDeltas: { incidentRate: -5, welfareDebt: -4, successIndex: 5 },
          },
          {
            id: "quarantine-replace",
            label: "Quarantine and replace dependency",
            summary: "Quarantine and replace. Good control improvement.",
            metricDeltas: { controlAdoption: 4, welfareDebt: -3, successIndex: 3 },
          },
          {
            id: "monitor-only",
            label: "Monitor and document; defer full remediation",
            summary: "Monitor and document. Debt remains.",
            metricDeltas: { welfareDebt: 2, successIndex: 1 },
          },
        ],
      },
      {
        id: "round-2",
        title: "Long-term supply chain posture",
        messages: [
          "Leadership wants build and supply chain aligned with FAIR loss exposure and control effectiveness.",
        ],
        prompt: "How do you strengthen supply chain long term?",
        choices: [
          {
            id: "full-program",
            label: "Supply chain security program and signed artifacts",
            summary: "Full program and signing. Strong control and debt reduction.",
            metricDeltas: { controlAdoption: 7, welfareDebt: -6, systemReversibility: 4, debtIndex: -3 },
          },
          {
            id: "scan-and-review",
            label: "Vulnerability scanning and dependency review",
            summary: "Scanning and review. Moderate improvement.",
            metricDeltas: { controlAdoption: 5, welfareDebt: -3, successIndex: 3 },
          },
          {
            id: "accept-residual",
            label: "Accept residual supply chain risk",
            summary: "Document and accept. Debt remains.",
            metricDeltas: { welfareDebt: 2, debtIndex: 2 },
          },
        ],
      },
    ],
  },
];

